(load "quicklisp/setup.lisp")
(push #p"./" asdf:*central-registry*)
(require :golpito)
(setf golpito.model::*connection* (destructuring-bind (name-password-host-port db) (split-sequence:split-sequence #\/ (subseq *dburl* 11))
                                    (destructuring-bind (name-password host-port) (split-sequence:split-sequence #\@ name-password-host-port)
                                      (destructuring-bind (name password) (split-sequence:split-sequence #\: name-password)
                                        (destructuring-bind (host port) (split-sequence:split-sequence #\: host-port)
                                          (list db name password host :port (parse-integer port)))))))
(restas:start :golpito :port *port*)
(setf hunchentoot:*catch-errors-p* nil)
(loop (sleep 60))